React application - Task # 9
Kalvarado07/padawan_training pull request #5
Opened 2022-08-22 20:35 UTC by Kalvarado07

# Pull Request
## Description
Build the website from 2.8.2. Task # 3 - One Piece Website using React.js
Fixes  ([ticket link](https://trello.com/c/ULSL63Iy))
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## How Has This Been Tested?
Tested with Chrome and Edge

2022-08-24 16:03 UTC, ochavarria requested changes

2022-08-24 16:03 UTC, ochavarria commented on task9/src/components/App/App.js
> +          <div className="wrapper__sinopsis-container">
Please implement components. Instead of having a <div> ..... </div> create a component called "sinopsis", and send all the data in parameters ( image and text ) try to breakdown the different parts of the components as parameters. Should have something like <Sipnosis image={image} header={"text" } props={...props} />

2022-08-24 16:03 UTC, ochavarria commented on task9/src/components/App/App.js
> +      <div id="characters" className="wrapper__content-section">
Same implement a component called character with the req. data passed by parameter.

2022-08-24 16:03 UTC, ochavarria commented on task9/src/components/App/App.js
> +        <div className="wrapper__grid-container--four-col">
Implement a component called character and import it in characters.

2022-08-24 16:03 UTC, ochavarria commented on task9/src/components/App/App.js
> +            <li>Islands</li>
Same as Characters, for Islands.

2022-08-24 16:03 UTC, ochavarria commented on task9/src/components/App/App.js
> +      <div id="mis-objects" className="wrapper__content-section">
Same.

2022-08-31 18:17 UTC, Kalvarado07 commented on task9/src/components/App/App.js
> +      <div id="characters" className="wrapper__content-section">
The changes requested were implemented on the last commit.

Thank you.

2022-08-31 18:17 UTC, Kalvarado07 commented on task9/src/components/App/App.js
> +      <div id="mis-objects" className="wrapper__content-section">
The changes requested were implemented on the last commit.

Thank you.

2022-08-31 18:17 UTC, Kalvarado07 commented on task9/src/components/App/App.js
> +        <div className="wrapper__grid-container--four-col">
The changes requested were implemented on the last commit.

Thank you.

2022-08-31 22:31 UTC, ochavarria commented on OnePiece/assets/css/style.scss
> +  .nav {
Avoid having files this big by creating style component file, in this case a .nav file.

2022-08-31 22:31 UTC, ochavarria commented on OnePiece/assets/css/style.scss
> +  #nav__checkbox:checked~ul.nav__menu li {
Don't target the id or the tags, as per is not a BEM practice.

2022-08-31 22:33 UTC, ochavarria commented on OnePiece/assets/css/style.scss
> +        margin: 0%;
instead of adding 0px, 0% 0 rem etc .. just add 0

2022-08-31 22:36 UTC, ochavarria commented on task9/src/components/App/App.js
> +          <Character data={chars[0]} />
You can add a .map in order to iterate all chars. 
Like: 
`<cardsection>`
{chars.map((char)=>{
`<Character data={char}>`
})}
`</cardsection>`

2022-09-01 15:12 UTC, merged